name: customer_churn_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.8
  - scikit-learn==0.24.1
  - shap==0.40.0
  - joblib==1.0.1
  - pandas==1.2.4
  - numpy==1.20.1
  - matplotlib==3.3.4
  - seaborn==0.11.2
  - pylint==2.7.4
  - pytest==6.2
  - autopep8==1.5.6